### ISSUE TITLE
Math operations

### ISSUE THREAD

**Issue by phueper** [pithu/js-joda#12]
all Math operations (div, modulo, ...) we are using should be wrapped and functions in `MathUtils` added for them. 

We expect to have problems with large integer number calculations so wrapping them now in preparation to handle big integer calculations in the future seems like a good idea

**Comment by phueper** [comment]
@pithu : /me thinks this is done for the current code as far as i see/remember?

**Comment by pithu** [comment]
@phueper yes i think so. There might be some rare places, where we oversee it, but it is easy to fix. 

btw: large (pseudo) integer number calculations seems to work quite well. I could not find any issues and we have now hundreds of tests with small and large numbers. As a rule of thumb, first multiply all values, do the division afterwards.
