### ISSUE TITLE
Why JodaTime; why not java.time?

### ISSUE THREAD

**Issue by mj1856** [pithu/js-joda#13]
As you probably know, Joda-Time influenced JSR-310, which became `java.time` in Java 8.  Several things were changed along the way, as described by Stephen Colebourne here: http://blog.joda.org/2009/11/why-jsr-310-isn-joda-time_4941.html

So - is this a Joda Time port to JavaScript, or a java.time port to JavaScript?   If the former, then *why*, considering the improvements and the young state of this port.  If the latter, then the description in the readme and project page should change.

FYI - Much of my experience comes from contributing to Noda Time, which is more like java.time than it is with Joda.  I'm also a collaborator on moment.js, but I've been toying with the idea of a Noda Time or java.time port to JavaScript for awhile now, so I'd be happy to help where I can.

Time zones are going to be the biggest challenge. :)

**Comment by phueper** [comment]
Hi @mj1856,

thank you for your input, it is very much welcome and we would love contributions.

As discussed in #10 and also #1 probably not clear enough in the README, we try to port the JSR-310 to JS in js-joda. 
For licensing reasons (we would like to use BSD License) we will not use the java.time implementation from OpenJDK as reference but rather the threetenbp backport project but the API is as far as we see right now very similar so this shouldn't make much of a difference for the JS Port

We'll try to clarify this in the README, and also the licensing issue.

Regarding the timezones: we also see this as a major point, that is why we currently plan to release a M1 Milestone for the basic API (see https://github.com/pithu/js-joda/milestones for the description of that milestone) that does not need TimeZone conversion support but already creates a usable library and then add Timezone support in further milestones. 
Documenting this roadmap is also something we have on our list of TODOs as next steps :)

Regards, Pattrick
