### ISSUE TITLE
cheat sheet navigation menu side bar

### ISSUE THREAD

**Issue by pithu** [pithu/js-joda#21]
Would be nice to have a menu side bar for navigating through the very long documentation of the cheat sheet at http://pithu.github.io/js-joda/cheat-sheet.html. 

AT the moment we are using a half automatic process to generate the cheatsheet.html page. We maintaining the CheatSheet.md. The npm task `npm run build-readme2html` generates a html snippet of the md content. the snippet is manually inserted into the gh-pages/cheat-sheet.html. 

One of many possible solution could be, to find a kind of self generating "table of content" javascript side menu bar library, that is generated automatically by the h tags of the dom tree.

**Comment by pithu** [comment]
A toc for the md file would be nice as well

**Comment by timaschew** [comment]
fa5ba9b is not deployed, right? I don't see any TOC on the docs page.
You wrote `have at least a very basic ..`, how your dream TOC would look like?

**Comment by pithu** [comment]
It should be generated automatically, with an easy, simple, transparent tool. a half automatically step would be ok for me. i gave http://doctoc.herokuapp.com/ a try, but it did not work for me.

My Dream would be something like a tag in the md files that automatically generates and inserts the toc. Without the need of any complicated scripts or configurations.

Same for the cheat-sheet.html page. Something like a javascipt lib that automatically creates and inserts a TOC out of the header elements of a dom tree.

**Comment by timaschew** [comment]
Ah okay, but the generated content is oaky as it is like in fa5ba9b ?

> Same for the cheat-sheet.html page

And about what (if not about the cheat-sheet) do you wrote in the paragraph above?

**Comment by pithu** [comment]
About the CheatSheet.md file. The cheat-sheet.html file is generated from the md file.

**Comment by lbilharz** [comment]
Is this issue solved? 
At least http://pithu.github.io/js-joda/cheat-sheet.html contains a TOC now.

**Comment by pithu** [comment]
@timaschew provided a dynamic toc generator for md and html files, i want to give it a try first.

**Comment by timaschew** [comment]
Voilà http://timaschew.github.io/auto-toc.js/

**Comment by pithu** [comment]
solved by https://github.com/pithu/js-joda/pull/27
