### ISSUE TITLE
travis is failing sometimes

### ISSUE THREAD

**Issue by timaschew** [pithu/js-joda#30]
I didn't change any code of the librariy itself in #28 but one test failed.
Seems that 2000ms is not enough anymore.

```
1) org.threeten.bp.temporal.TestIsoFields test_loop:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by pithu** [comment]
lets give commit 9604dab0d114ab91bf8139e2c452befc310dd085 a try
